version: "3.0"

services:
  react:
    build: 
      context: ./front_end
      dockerfile: dockerfile
    expose: 
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - "./front_end:/app"
    environment:
      - NODE_ENV=development
      # CHOKIDAR_USEPOLLING=ture은 App이 수정되었을 경우 Reload이 가능하도록 하는 설정
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty : true
    networks:
      - webnet
    restart: always

  flask:
    build:
      context: ./flask/detection
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command:
      flask run --host=0.0.0.0
      # nohup flask run --host=0.0.0.0
    networks: 
      - webnet      
    restart: always

networks:
  webnet:
    driver: bridge