version: "3.0"

services:
  flask:
    build:
      context: ./flask/detection
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command:
      flask run --host=0.0.0.0
      # nohup flask run --host=0.0.0.0
    networks: 
      - webnet      
    restart: always

networks:
  webnet:
    driver: bridge