FROM ubuntu

WORKDIR /app

COPY . .
ARG DEBIAN_FRONTEND=noninteractive 
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y python3 python3-pip \
    tesseract-ocr tesseract-ocr-kor git

RUN pip3 install --no-cache-dir -r requirements.txt
#RUN git clone https://github.com/ultralytics/yolov5 