"""empty message

Revision ID: 775e07c161c0
Revises: 
Create Date: 2021-06-24 17:19:03.430743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775e07c161c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.Column('customer', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail',
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.Column('where', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('parking',
    sa.Column('parking_nubmer', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('where', sa.String(length=100), nullable=False),
    sa.Column('in_time', sa.DateTime(), nullable=True),
    sa.Column('out_time', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['user.customer'], ),
    sa.ForeignKeyConstraint(['where'], ['detail.where'], ),
    sa.PrimaryKeyConstraint('parking_nubmer')
    )
    op.create_table('where_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('where', sa.String(length=100), nullable=False),
    sa.Column('max_car_num', sa.Integer(), nullable=True),
    sa.Column('car_num', sa.Integer(), nullable=True),
    sa.Column('cost_per_10min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['where'], ['detail.where'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('where_detail')
    op.drop_table('parking')
    op.drop_table('detail')
    op.drop_table('answer')
    op.drop_table('user')
    op.drop_table('question')
    # ### end Alembic commands ###
